export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const SET_BRAND = "SET_BRAND";
export const SET_SUB_CATEGORY = "SET_SUB_CATEGORY";
export const GET_SUB_CATEGORIES_OF_CATEGORY = "GET_SUB_CATEGORIES_OF_CATEGORY";
