export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const SET_BRAND = "SET_BRAND";
export const SET_SUB_CATEGORY = "SET_SUB_CATEGORY";
export const GET_SUB_CATEGORIES_OF_CATEGORY = "GET_SUB_CATEGORIES_OF_CATEGORY";
export const SET_PRODUCT = "SET_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const GET_SPESIFIC_CATEGORY = "GET_SPESIFIC_CATEGORY";
export const GET_SPESIFIC_BRAND = "GET_SPESIFIC_BRAND";
export const GET_SPECIFIC_PRODUCTS_WITH_CATEGORY =
  "GET_SPECIFIC_PRODUCTS_WITH_CATEGORY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const ERROR = "ERROR";
